stages:
  - build
  - test
  - push_to_dockerhub
  - deploy

build_job:
  stage: build
  image: docker:24.0.5
  script:
    - docker build -t node-app:latest .
  tags:
    - bash

test_job:
  stage: test
  script:
    - echo "testing starts.. ... ... . .. "
  tags:
    - bash

push_jobs:
  stage: push_to_dockerhub
  image: docker:24.0.5
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - docker image tag node-app:latest $DOCKERHUB_USER/node-app:latest
    - docker push $DOCKERHUB_USER/node-app:latest
  tags:
    - bash

deploy_job:
  stage: deploy
  image: docker:24.0.5
  script:
    - docker compose up -d
  tags:
    - bash